apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: devops
data:
  nginx.conf: |
      server {
        server_name wordpress.test.com;
        listen 80 default_server;
        location / {
          root /usr/share/nginx/html/wordpress;
          index index.php index.html index.htm;
        }
        location ~ \.php$ {
                root /var/www/html/wordpress;
                fastcgi_pass php-wordpress:9000;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include /etc/nginx/fastcgi_params;
        }
      }
